---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: jakob-eu-west
    instance_type: t2.small
    security_group: sg-b7d5c7d2
    image: ami-47a23a30
    region: eu-west-1
    vpc_subnet_id: subnet-5722e020
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ vpc_subnet_id }}"
         assign_public_ip: yes
         instance_tags:
           Name: jakob-test
      register: ec2
    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

# - name: Configure instance(s)
#   hosts: launched
#   sudo: True
#   gather_facts: True
#   roles:
#     - my_awesome_role
#     - my_awesome_test

# - name: Terminate instances
#   hosts: localhost
#   connection: local
#   tasks:
#     - name: Terminate instances that were previously launched
#       ec2:
#         state: 'absent'
#         instance_ids: '{{ ec2.instance_ids }}'
